/**
 * Готовые пресеты шаблонов сертификатов
 * 
 * Содержит JSON-структуры для быстрого старта с красивым дизайном
 */

import type { CertificateTemplateData, TemplateElement } from '~/types/certificate';

// Генерация уникального ID для элементов (без внешних зависимостей)
function generateId(): string {
  return 'el_' + Math.random().toString(36).substring(2, 11);
}

/**
 * Классический шаблон сертификата
 * Золотистая рамка, классический шрифт, традиционный дизайн
 */
export function getClassicPreset(): CertificateTemplateData {
  const width = 1123;
  const height = 794;

  return {
    layout: 'A4_landscape',
    width,
    height,
    background: {
      type: 'color',
      value: '#FFF8E7',
    },
    elements: [
      // Рамка (прямоугольник)
      {
        id: generateId(),
        type: 'shape',
        x: 30,
        y: 30,
        width: width - 60,
        height: height - 60,
        rotation: 0,
        zIndex: 1,
        locked: false,
        shapeType: 'rectangle',
        fillColor: 'transparent',
        strokeColor: '#D4A853',
        strokeWidth: 3,
      },
      // Внутренняя рамка
      {
        id: generateId(),
        type: 'shape',
        x: 45,
        y: 45,
        width: width - 90,
        height: height - 90,
        rotation: 0,
        zIndex: 2,
        locked: false,
        shapeType: 'rectangle',
        fillColor: 'transparent',
        strokeColor: '#D4A853',
        strokeWidth: 1,
      },
      // Заголовок "СЕРТИФИКАТ"
      {
        id: generateId(),
        type: 'text',
        x: width / 2 - 200,
        y: 100,
        width: 400,
        height: 60,
        rotation: 0,
        zIndex: 10,
        locked: false,
        content: 'СЕРТИФИКАТ',
        fontFamily: 'Georgia',
        fontSize: 48,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#8B6914',
        lineHeight: 1.2,
      },
      // Подзаголовок
      {
        id: generateId(),
        type: 'text',
        x: width / 2 - 200,
        y: 165,
        width: 400,
        height: 30,
        rotation: 0,
        zIndex: 11,
        locked: false,
        content: 'о повышении квалификации',
        fontFamily: 'Georgia',
        fontSize: 18,
        fontWeight: 'normal',
        fontStyle: 'italic',
        textAlign: 'center',
        color: '#666666',
        lineHeight: 1.2,
      },
      // ФИО (переменная)
      {
        id: generateId(),
        type: 'variable',
        x: width / 2 - 300,
        y: 240,
        width: 600,
        height: 50,
        rotation: 0,
        zIndex: 12,
        locked: false,
        variableKey: 'student.fullName',
        placeholder: 'Иванов Иван Иванович',
        fontFamily: 'Georgia',
        fontSize: 32,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#1a1a1a',
        lineHeight: 1.2,
      },
      // Линия под ФИО
      {
        id: generateId(),
        type: 'shape',
        x: 200,
        y: 295,
        width: width - 400,
        height: 2,
        rotation: 0,
        zIndex: 13,
        locked: false,
        shapeType: 'line',
        fillColor: 'transparent',
        strokeColor: '#D4A853',
        strokeWidth: 1,
      },
      // Текст "прошёл(а) обучение"
      {
        id: generateId(),
        type: 'text',
        x: width / 2 - 200,
        y: 320,
        width: 400,
        height: 30,
        rotation: 0,
        zIndex: 14,
        locked: false,
        content: 'успешно завершил(а) обучение по программе',
        fontFamily: 'Georgia',
        fontSize: 16,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#444444',
        lineHeight: 1.3,
      },
      // Название курса (переменная)
      {
        id: generateId(),
        type: 'variable',
        x: 100,
        y: 370,
        width: width - 200,
        height: 60,
        rotation: 0,
        zIndex: 15,
        locked: false,
        variableKey: 'course.name',
        placeholder: 'Название курса повышения квалификации',
        fontFamily: 'Georgia',
        fontSize: 22,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#1a1a1a',
        lineHeight: 1.3,
      },
      // Часы (переменная)
      {
        id: generateId(),
        type: 'text',
        x: width / 2 - 150,
        y: 440,
        width: 100,
        height: 30,
        rotation: 0,
        zIndex: 16,
        locked: false,
        content: 'в объёме',
        fontFamily: 'Georgia',
        fontSize: 14,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'right',
        color: '#666666',
        lineHeight: 1.3,
      },
      {
        id: generateId(),
        type: 'variable',
        x: width / 2 - 40,
        y: 440,
        width: 50,
        height: 30,
        rotation: 0,
        zIndex: 17,
        locked: false,
        variableKey: 'course.totalHours',
        placeholder: '72',
        fontFamily: 'Georgia',
        fontSize: 18,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#1a1a1a',
        lineHeight: 1.3,
      },
      {
        id: generateId(),
        type: 'text',
        x: width / 2 + 20,
        y: 440,
        width: 150,
        height: 30,
        rotation: 0,
        zIndex: 18,
        locked: false,
        content: 'академических часов',
        fontFamily: 'Georgia',
        fontSize: 14,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#666666',
        lineHeight: 1.3,
      },
      // Номер сертификата
      {
        id: generateId(),
        type: 'text',
        x: 80,
        y: height - 120,
        width: 200,
        height: 25,
        rotation: 0,
        zIndex: 20,
        locked: false,
        content: 'Сертификат №',
        fontFamily: 'Georgia',
        fontSize: 12,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#666666',
        lineHeight: 1.2,
      },
      {
        id: generateId(),
        type: 'variable',
        x: 80,
        y: height - 95,
        width: 200,
        height: 25,
        rotation: 0,
        zIndex: 21,
        locked: false,
        variableKey: 'certificate.number',
        placeholder: 'ATC24_IT_0001',
        fontFamily: 'Georgia',
        fontSize: 14,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#1a1a1a',
        lineHeight: 1.2,
      },
      // Дата выдачи
      {
        id: generateId(),
        type: 'text',
        x: width / 2 - 100,
        y: height - 120,
        width: 200,
        height: 25,
        rotation: 0,
        zIndex: 22,
        locked: false,
        content: 'Дата выдачи',
        fontFamily: 'Georgia',
        fontSize: 12,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#666666',
        lineHeight: 1.2,
      },
      {
        id: generateId(),
        type: 'variable',
        x: width / 2 - 100,
        y: height - 95,
        width: 200,
        height: 25,
        rotation: 0,
        zIndex: 23,
        locked: false,
        variableKey: 'certificate.issueDateFormatted',
        placeholder: '26 декабря 2024 года',
        fontFamily: 'Georgia',
        fontSize: 14,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#1a1a1a',
        lineHeight: 1.2,
      },
      // QR-код
      {
        id: generateId(),
        type: 'qr',
        x: width - 150,
        y: height - 150,
        width: 100,
        height: 100,
        rotation: 0,
        zIndex: 30,
        locked: false,
        dataSource: 'certificate_url',
        size: 100,
        color: '#1a1a1a',
        backgroundColor: '#FFFFFF',
      },
    ] as TemplateElement[],
  };
}

/**
 * Современный шаблон сертификата
 * Градиентный фон, современный шрифт, геометрические акценты
 */
export function getModernPreset(): CertificateTemplateData {
  const width = 1123;
  const height = 794;

  return {
    layout: 'A4_landscape',
    width,
    height,
    background: {
      type: 'color',
      value: '#F8FAFC',
    },
    elements: [
      // Акцентная полоса слева
      {
        id: generateId(),
        type: 'shape',
        x: 0,
        y: 0,
        width: 80,
        height: height,
        rotation: 0,
        zIndex: 1,
        locked: false,
        shapeType: 'rectangle',
        fillColor: '#4F46E5',
        strokeColor: 'transparent',
        strokeWidth: 0,
      },
      // Декоративный круг
      {
        id: generateId(),
        type: 'shape',
        x: width - 200,
        y: -100,
        width: 300,
        height: 300,
        rotation: 0,
        zIndex: 2,
        locked: false,
        shapeType: 'circle',
        fillColor: '#EEF2FF',
        strokeColor: 'transparent',
        strokeWidth: 0,
      },
      // Заголовок
      {
        id: generateId(),
        type: 'text',
        x: 120,
        y: 80,
        width: 500,
        height: 50,
        rotation: 0,
        zIndex: 10,
        locked: false,
        content: 'CERTIFICATE',
        fontFamily: 'Inter',
        fontSize: 42,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#1E293B',
        lineHeight: 1.2,
      },
      {
        id: generateId(),
        type: 'text',
        x: 120,
        y: 130,
        width: 300,
        height: 30,
        rotation: 0,
        zIndex: 11,
        locked: false,
        content: 'OF COMPLETION',
        fontFamily: 'Inter',
        fontSize: 16,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#64748B',
        lineHeight: 1.2,
      },
      // ФИО
      {
        id: generateId(),
        type: 'text',
        x: 120,
        y: 200,
        width: 400,
        height: 25,
        rotation: 0,
        zIndex: 12,
        locked: false,
        content: 'This is to certify that',
        fontFamily: 'Inter',
        fontSize: 14,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#94A3B8',
        lineHeight: 1.2,
      },
      {
        id: generateId(),
        type: 'variable',
        x: 120,
        y: 230,
        width: 600,
        height: 45,
        rotation: 0,
        zIndex: 13,
        locked: false,
        variableKey: 'student.fullName',
        placeholder: 'Иванов Иван Иванович',
        fontFamily: 'Inter',
        fontSize: 36,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#1E293B',
        lineHeight: 1.2,
      },
      // Линия
      {
        id: generateId(),
        type: 'shape',
        x: 120,
        y: 285,
        width: 600,
        height: 3,
        rotation: 0,
        zIndex: 14,
        locked: false,
        shapeType: 'rectangle',
        fillColor: '#E2E8F0',
        strokeColor: 'transparent',
        strokeWidth: 0,
      },
      // Курс
      {
        id: generateId(),
        type: 'text',
        x: 120,
        y: 310,
        width: 600,
        height: 25,
        rotation: 0,
        zIndex: 15,
        locked: false,
        content: 'has successfully completed the training program',
        fontFamily: 'Inter',
        fontSize: 14,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#94A3B8',
        lineHeight: 1.2,
      },
      {
        id: generateId(),
        type: 'variable',
        x: 120,
        y: 345,
        width: width - 300,
        height: 60,
        rotation: 0,
        zIndex: 16,
        locked: false,
        variableKey: 'course.name',
        placeholder: 'Название курса',
        fontFamily: 'Inter',
        fontSize: 24,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#4F46E5',
        lineHeight: 1.3,
      },
      // Часы
      {
        id: generateId(),
        type: 'variable',
        x: 120,
        y: 420,
        width: 60,
        height: 35,
        rotation: 0,
        zIndex: 17,
        locked: false,
        variableKey: 'course.totalHours',
        placeholder: '72',
        fontFamily: 'Inter',
        fontSize: 28,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#1E293B',
        lineHeight: 1.2,
      },
      {
        id: generateId(),
        type: 'text',
        x: 180,
        y: 428,
        width: 200,
        height: 25,
        rotation: 0,
        zIndex: 18,
        locked: false,
        content: 'hours',
        fontFamily: 'Inter',
        fontSize: 16,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#64748B',
        lineHeight: 1.2,
      },
      // Дата и номер внизу
      {
        id: generateId(),
        type: 'text',
        x: 120,
        y: height - 100,
        width: 100,
        height: 20,
        rotation: 0,
        zIndex: 20,
        locked: false,
        content: 'DATE',
        fontFamily: 'Inter',
        fontSize: 10,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#94A3B8',
        lineHeight: 1.2,
      },
      {
        id: generateId(),
        type: 'variable',
        x: 120,
        y: height - 80,
        width: 200,
        height: 25,
        rotation: 0,
        zIndex: 21,
        locked: false,
        variableKey: 'certificate.issueDate',
        placeholder: '26.12.2024',
        fontFamily: 'Inter',
        fontSize: 16,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#1E293B',
        lineHeight: 1.2,
      },
      {
        id: generateId(),
        type: 'text',
        x: 350,
        y: height - 100,
        width: 100,
        height: 20,
        rotation: 0,
        zIndex: 22,
        locked: false,
        content: 'CERTIFICATE NO.',
        fontFamily: 'Inter',
        fontSize: 10,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#94A3B8',
        lineHeight: 1.2,
      },
      {
        id: generateId(),
        type: 'variable',
        x: 350,
        y: height - 80,
        width: 250,
        height: 25,
        rotation: 0,
        zIndex: 23,
        locked: false,
        variableKey: 'certificate.number',
        placeholder: 'ATC24_IT_0001',
        fontFamily: 'Inter',
        fontSize: 16,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#1E293B',
        lineHeight: 1.2,
      },
      // QR в правом нижнем углу
      {
        id: generateId(),
        type: 'qr',
        x: width - 160,
        y: height - 160,
        width: 120,
        height: 120,
        rotation: 0,
        zIndex: 30,
        locked: false,
        dataSource: 'certificate_url',
        size: 120,
        color: '#4F46E5',
        backgroundColor: '#FFFFFF',
      },
    ] as TemplateElement[],
  };
}

/**
 * Минималистичный шаблон сертификата
 * Чистый белый фон, минимум деталей, фокус на содержании
 */
export function getMinimalPreset(): CertificateTemplateData {
  const width = 1123;
  const height = 794;

  return {
    layout: 'A4_landscape',
    width,
    height,
    background: {
      type: 'color',
      value: '#FFFFFF',
    },
    elements: [
      // Тонкая линия сверху
      {
        id: generateId(),
        type: 'shape',
        x: 100,
        y: 60,
        width: width - 200,
        height: 2,
        rotation: 0,
        zIndex: 1,
        locked: false,
        shapeType: 'rectangle',
        fillColor: '#1a1a1a',
        strokeColor: 'transparent',
        strokeWidth: 0,
      },
      // Заголовок
      {
        id: generateId(),
        type: 'text',
        x: 100,
        y: 100,
        width: width - 200,
        height: 50,
        rotation: 0,
        zIndex: 10,
        locked: false,
        content: 'Сертификат',
        fontFamily: 'Inter',
        fontSize: 36,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#1a1a1a',
        lineHeight: 1.2,
      },
      // ФИО
      {
        id: generateId(),
        type: 'variable',
        x: 100,
        y: 220,
        width: width - 200,
        height: 50,
        rotation: 0,
        zIndex: 11,
        locked: false,
        variableKey: 'student.fullName',
        placeholder: 'Иванов Иван Иванович',
        fontFamily: 'Inter',
        fontSize: 42,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#1a1a1a',
        lineHeight: 1.2,
      },
      // Текст
      {
        id: generateId(),
        type: 'text',
        x: 100,
        y: 310,
        width: width - 200,
        height: 30,
        rotation: 0,
        zIndex: 12,
        locked: false,
        content: 'прошёл(а) обучение по программе',
        fontFamily: 'Inter',
        fontSize: 16,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#666666',
        lineHeight: 1.2,
      },
      // Курс
      {
        id: generateId(),
        type: 'variable',
        x: 100,
        y: 360,
        width: width - 200,
        height: 60,
        rotation: 0,
        zIndex: 13,
        locked: false,
        variableKey: 'course.name',
        placeholder: 'Название курса',
        fontFamily: 'Inter',
        fontSize: 24,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#1a1a1a',
        lineHeight: 1.3,
      },
      // Часы
      {
        id: generateId(),
        type: 'text',
        x: 100,
        y: 440,
        width: width - 200,
        height: 25,
        rotation: 0,
        zIndex: 14,
        locked: false,
        content: 'Объём:',
        fontFamily: 'Inter',
        fontSize: 14,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'center',
        color: '#999999',
        lineHeight: 1.2,
      },
      {
        id: generateId(),
        type: 'variable',
        x: width / 2 + 30,
        y: 440,
        width: 100,
        height: 25,
        rotation: 0,
        zIndex: 15,
        locked: false,
        variableKey: 'course.totalHours',
        placeholder: '72',
        fontFamily: 'Inter',
        fontSize: 14,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#1a1a1a',
        lineHeight: 1.2,
      },
      // Линия снизу
      {
        id: generateId(),
        type: 'shape',
        x: 100,
        y: height - 100,
        width: width - 200,
        height: 1,
        rotation: 0,
        zIndex: 20,
        locked: false,
        shapeType: 'rectangle',
        fillColor: '#E5E7EB',
        strokeColor: 'transparent',
        strokeWidth: 0,
      },
      // Дата и номер
      {
        id: generateId(),
        type: 'variable',
        x: 100,
        y: height - 80,
        width: 200,
        height: 25,
        rotation: 0,
        zIndex: 21,
        locked: false,
        variableKey: 'certificate.issueDate',
        placeholder: '26.12.2024',
        fontFamily: 'Inter',
        fontSize: 14,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
        color: '#666666',
        lineHeight: 1.2,
      },
      {
        id: generateId(),
        type: 'variable',
        x: width - 300,
        y: height - 80,
        width: 200,
        height: 25,
        rotation: 0,
        zIndex: 22,
        locked: false,
        variableKey: 'certificate.number',
        placeholder: 'ATC24_IT_0001',
        fontFamily: 'Inter',
        fontSize: 14,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'right',
        color: '#666666',
        lineHeight: 1.2,
      },
      // QR в центре снизу
      {
        id: generateId(),
        type: 'qr',
        x: width / 2 - 40,
        y: height - 95,
        width: 80,
        height: 80,
        rotation: 0,
        zIndex: 30,
        locked: false,
        dataSource: 'certificate_url',
        size: 80,
        color: '#1a1a1a',
        backgroundColor: '#FFFFFF',
      },
    ] as TemplateElement[],
  };
}

/**
 * Получить пресет по имени
 */
export function getPreset(name: 'classic' | 'modern' | 'minimal'): CertificateTemplateData {
  switch (name) {
    case 'classic':
      return getClassicPreset();
    case 'modern':
      return getModernPreset();
    case 'minimal':
      return getMinimalPreset();
    default:
      return getClassicPreset();
  }
}

/**
 * Список доступных пресетов
 */
export const TEMPLATE_PRESETS = [
  {
    id: 'classic',
    name: 'Классический',
    description: 'Золотистая рамка, традиционный стиль',
  },
  {
    id: 'modern',
    name: 'Современный',
    description: 'Градиенты, геометрические акценты',
  },
  {
    id: 'minimal',
    name: 'Минималистичный',
    description: 'Чистый дизайн, фокус на контенте',
  },
] as const;
